## Data cleaning

In this section, we first see the data structure and identify data attributes. We then clean the data, including removing bad rows, bad attributes, imputing missing values, etc.

First of all, we import the necessary packages to the Jupyter notebook:

In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
np.random.seed(1)

We load the raw data.

In [3]:
df = pd.read_csv('smoking.csv',sep= ',')

In [4]:
df.head()

age  gender  A1  A2_completed_education  A3  A4  A5   A6   A7   A8  ...  \
0   35       2   1                       2   2   1 NaN  2.0  3.0  1.0  ...   
1   34       1   4                       3   3   1 NaN  2.0  3.0  1.0  ...   
2   37       2   3                       3   3   1 NaN  4.0  2.0  1.0  ...   
3   37       2   3                       3   3   1 NaN  4.0  2.0  1.0  ...   
4   35       2   2                       3   3   3 NaN  NaN  NaN  NaN  ...   

   Low  Middle  High  Not_applicable  Smoke_daily  Smoke_less_then_daily  \
0  1.0     0.0   0.0             0.0          1.0                    0.0   
1  1.0     0.0   0.0             0.0          1.0                    0.0   
2  0.0     0.0   1.0             0.0          1.0                    0.0   
3  0.0     0.0   1.0             0.0          1.0                    0.0   
4  0.0     0.0   1.0             0.0          0.0                    0.0   

   Smoked_in_the_past  Never_smoker  a62_income  a4_smoking_status  
0                 0.0           0.0         1.0                1.0  
1                 0.0           0.0         1.0                1.0  
2                 0.0           0.0         3.0                1.0  
3                 0.0           0.0         3.0                1.0  
4                 1.0           0.0         3.0                3.0  

[5 rows x 119 columns]

There are 118 attributes: <br/>


and 1 class: health status with 1 and 0 representing healthy and not healthy.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1588 entries, 0 to 1587
Columns: 119 entries, age to a4_smoking_status
dtypes: float64(49), int64(70)
memory usage: 1.4 MB


We see that many of the 'A' variables contain so many missing values, so we will remove these attributes, along with 'SalesHighSupport' and 'a62_income'.

In [6]:
df = df.drop(['A5', 'A6', 'A7','A8','A10','A11','A12','A13','A14','A15','A27','A28','A29','A36','A41','A42','A43','A44','A45','A63','A64','A65','A66','SalesHighSupport','a62_income'],axis=1)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1588 entries, 0 to 1587
Data columns (total 94 columns):
age                             1588 non-null int64
gender                          1588 non-null int64
A1                              1588 non-null int64
A2_completed_education          1588 non-null int64
A3                              1588 non-null int64
A4                              1588 non-null int64
A9                              1588 non-null int64
A16                             1587 non-null float64
A17                             1587 non-null float64
A18                             1588 non-null int64
A19                             1588 non-null int64
A20                             1588 non-null int64
A21                             1588 non-null int64
A22                             1588 non-null int64
A23                             1588 non-null int64
A24                             1588 non-null int64
A25                             1588 non-null int64
A26  

To clearn the data, we first replace the empty value by `nan`.

In [8]:
# replace empty by nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df = df.replace('99',np.nan,regex=True)
df = df.replace(99,np.nan,regex=True)
df

age  gender  A1  A2_completed_education  A3  A4   A9  A16  A17  A18  \
0      35       2   1                       2   2   1  6.0  0.0  0.0    0   
1      34       1   4                       3   3   1  6.0  1.0  1.0    1   
2      37       2   3                       3   3   1  6.0  1.0  1.0    0   
3      37       2   3                       3   3   1  6.0  1.0  1.0    0   
4      35       2   2                       3   3   3  6.0  1.0  1.0    0   
5      29       2   5                       3   2   1  2.0  1.0  1.0    0   
6      48       1   2                       3   3   1  6.0  1.0  1.0    1   
7      41       2   5                       3   3   1  6.0  1.0  1.0    0   
8      15       1   5                       1   1   1  6.0  1.0  1.0    1   
9      37       2   1                       3   1   1  6.0  1.0  1.0    0   
10     56       1   1                       3   2   4  6.0  1.0  1.0    1   
11     23       2   5                       2   1   2  6.0  1.0  1.0    1   
12     49       2   1                       3   2   4  6.0  1.0  1.0    1   
13     36       2   2                       2   1   2  6.0  0.0  0.0    0   
14     34       2   1                       3   2   1  2.0  1.0  1.0    1   
15     32       1   1                       2   1   4  6.0  1.0  1.0    1   
16     38       1   1                       2   1   4  6.0  1.0  1.0    1   
17     44       1   1                       2   4   1  6.0  1.0  1.0    0   
18     51       1   3                       3   4   3  6.0  1.0  1.0    1   
19     29       1   1                       3   2   1  6.0  1.0  1.0    1   
20     23       1   5                       2   1   4  6.0  1.0  1.0    1   
21     32       1   1                       3   1   4  6.0  1.0  1.0    1   
22     27       1   2                       3   3   4  6.0  1.0  1.0    1   
23     62       1   4                       3   3   3  6.0  1.0  1.0    1   
24     67       1   4                       2   5   3  6.0  1.0  1.0    1   
25     34       1   1                       3   2   1  6.0  1.0  1.0    0   
26     29       2   1                       3   1   1  6.0  0.0  0.0    0   
27     60       2   1                       1   5   3  6.0  1.0  1.0    1   
28     65       1   1                       1   2   4  6.0  1.0  1.0    1   
29     54       2   3                       2   2   4  6.0  1.0  1.0    1   
...   ...     ...  ..                     ...  ..  ..  ...  ...  ...  ...   
1558   61       1   2                       2   4   2  6.0  0.0  0.0    0   
1559   36       1   1                       3   3   4  6.0  0.0  0.0    1   
1560   44       2   1                       3   3   2  6.0  1.0  1.0    0   
1561   31       2   5                       3   3   1  3.0  1.0  1.0    0   
1562   35       2   2                       3   3   3  6.0  1.0  1.0    0   
1563   14       2   5                       1   1   1  6.0  0.0  0.0    0   
1564   15       1   5                       1   1   2  6.0  0.0  0.0    0   
1565   61       2   1                       1   2   4  6.0  1.0  1.0    1   
1566   51       2   1                       2   4   1  6.0  1.0  0.0    1   
1567   34       1   3                       3   3   1  6.0  1.0  1.0    1   
1568   37       1   5                       2   1   4  NaN  1.0  1.0    1   
1569   37       1   2                       3   1   1  6.0  0.0  0.0    0   
1570   44       2   1                       1   3   1  6.0  1.0  1.0    1   
1571   28       1   4                       3   2   4  6.0  1.0  1.0    1   
1572   29       1   2                       3   2   2  6.0  1.0  1.0    0   
1573   47       2   1                       1   2   1  6.0  0.0  0.0    0   
1574   70       1   4                       1   2   4  6.0  1.0  1.0    1   
1575   27       1   1                       2   2   4  6.0  1.0  1.0    1   
1576   57       2   1                       1   4   1  6.0  1.0  1.0    1   
1577   53       1   1                       3   2   4  6.0  1.0  1.0    1   
15

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1588 entries, 0 to 1587
Data columns (total 94 columns):
age                             1588 non-null int64
gender                          1588 non-null int64
A1                              1588 non-null int64
A2_completed_education          1588 non-null int64
A3                              1588 non-null int64
A4                              1588 non-null int64
A9                              1571 non-null float64
A16                             1587 non-null float64
A17                             1587 non-null float64
A18                             1588 non-null int64
A19                             1588 non-null int64
A20                             1588 non-null int64
A21                             1556 non-null float64
A22                             1585 non-null float64
A23                             1588 non-null int64
A24                             1588 non-null int64
A25                             1588 non-null int64

We find bad rows which contain too many missing values, then remove them.

In [10]:
# find bad rows having too many missing values
n_null = np.array(df.isnull().sum(axis=1))
bad_row = np.array([])
for t in range(len(n_null)):
    if n_null[t] > 4:
        #print(t)
        bad_row = np.append(bad_row,t)
        
print(bad_row)
print(len(bad_row))

# delete bad rows
df = df.drop(bad_row)
df.info()

[   0.   15.   16.   18.   19.   20.   21.   31.   45.   75.  104.  105.
  107.  108.  112.  146.  147.  148.  190. 1264. 1266. 1267. 1268. 1269.
 1288. 1289. 1293. 1294. 1316. 1364. 1369. 1392. 1406. 1560. 1565. 1568.
 1574. 1575. 1576. 1577. 1578. 1579. 1580. 1581. 1582. 1583. 1584. 1585.
 1586. 1587.]
50
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1538 entries, 1 to 1573
Data columns (total 94 columns):
age                             1538 non-null int64
gender                          1538 non-null int64
A1                              1538 non-null int64
A2_completed_education          1538 non-null int64
A3                              1538 non-null int64
A4                              1538 non-null int64
A9                              1522 non-null float64
A16                             1537 non-null float64
A17                             1537 non-null float64
A18                             1538 non-null int64
A19                             1538 non-null int64
A20   

The data still contain errors, such as `\t`, ` `, `\?`. We will delete `\t` and ` ` and convert `\?` to `np.nan`.

In [11]:
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?','np.nan',regex=True)

No variable type is object, so we will skip the next step.

In [12]:
#print(np.dtype(df['pcv']))

#df["pcv"] = pd.to_numeric(df.pcv, errors='coerce')

For convenience, we separate independents `X` and dependent `y` from the data.

In [13]:
X = df.drop('healthstatus3',axis=1)
y = df['healthstatus3']

In [14]:
np.savetxt('X.dat',X,fmt='%f')

We impute the missing value of X at each column by its median value.

In [15]:
from sklearn.base import TransformerMixin

class DataFrameImputer(TransformerMixin):
    def __init__(self):
        """Impute missing values.
        - Columns of dtype object are imputed with the most frequent value in column.
        - Columns of other types are imputed with mean of column.
        """
    def fit(self, X, y=None):
        self.fill = pd.Series([X[c].value_counts().index[0]
            # numerical --> mean, categorical --> median
            if X[c].dtype == np.dtype('O') else X[c].mean() for c in X], index=X.columns)  
                               
            # numerical, categorical --> median                   
            #if X[c].dtype == np.dtype('O') else X[c].median() for c in X], index=X.columns)
        return self

    def transform(self, X, y=None):
        return X.fillna(self.fill)

In [16]:
#X = DataFrameImputer().fit_transform(X)
#X.info()

Now, the data are completely clean. We convert attributes `X` and target `y` to numpy arrays and save them to files.

In [17]:
#X = np.array(X)
#y = np.array(y)
#Xy = np.hstack((X,y[:,np.newaxis]))

#np.savetxt('smoking_cleaned.dat',Xy,fmt='%s')

In [18]:
X = np.array(X)

In [19]:
i_complete = []
for i in range(X.shape[1]):
    n_missing = np.sum(np.isnan(X[:,i]))
    if n_missing == 0:
        i_complete.append(i)
        #print(i)
        #print(i,n_missing)
print(len(i_complete))

54


In [20]:
x = X[:,i_complete]
x.shape

(1538, 54)

In [21]:
l,n = x.shape
nu = np.array([len(np.unique(x[:,i])) for i in range(n)])
print('number of uniques of each variable:')
print(nu)

number of uniques of each variable:
[  58    2    5    3    5    4    2    2    2    3    3    3 1531   10
    5    2    3    7    3    2    2    2    4    2    2    2    2    2
    2    2    2    9    2    9    2    2    2    2    2    2    2    2
    2    2    2    2    2    2    2    2    2    2    2    4]


In [22]:
for i in range(n):    
    n_unique,n_count = np.unique(x[:,i],return_counts=True)
    if len(n_unique) < 5:
        print(i,n_unique,n_count)

1 [1. 2.] [893 645]
3 [1. 2. 3.] [479 553 506]
5 [1. 2. 3. 4.] [435 203  90 810]
6 [0. 1.] [ 462 1076]
7 [0. 1.] [ 210 1328]
8 [0. 1.] [ 206 1332]
9 [0. 1. 2.] [ 211 1326    1]
10 [0. 1. 2.] [ 206 1331    1]
11 [1. 2. 3.] [564 835 139]
15 [0. 1.] [816 722]
16 [0. 1. 2.] [397 583 558]
18 [0. 1. 2.] [ 193  133 1212]
19 [0. 1.] [1346  192]
20 [0. 1.] [1405  133]
21 [0. 1.] [ 326 1212]
22 [0. 1. 2. 3.] [1341  172   24    1]
23 [0. 1.] [ 266 1272]
24 [0. 1.] [ 260 1278]
25 [0. 1.] [ 256 1282]
26 [0. 1.] [ 240 1298]
27 [0. 1.] [ 220 1318]
28 [0. 1.] [ 238 1300]
29 [0. 1.] [ 307 1231]
30 [0. 1.] [ 237 1301]
32 [0. 1.] [  18 1520]
34 [0. 1.] [ 231 1307]
35 [0. 1.] [1283  255]
36 [0. 1.] [1242  296]
37 [0. 1.] [1212  326]
38 [0. 1.] [1250  288]
39 [0. 1.] [1165  373]
40 [0. 1.] [645 893]
41 [0. 1.] [893 645]
42 [0. 1.] [1059  479]
43 [0. 1.] [985 553]
44 [0. 1.] [1032  506]
45 [0. 1.] [1099  439]
46 [0. 1.] [980 558]
47 [0. 1.] [1015  523]
48 [0. 1.] [1520   18]
49 [0. 1.] [1103  435]
50 [0. 1.

In [23]:
np.unique(x[:,9])

array([0., 1., 2.])

In [24]:
np.where(x[:,9] == 2)

(array([1532]),)

In [25]:
np.where(x[:,10] == 2)

(array([1532]),)

In [26]:
np.where(x[:,22] == 3)

(array([9]),)

In [27]:
x = np.delete(x,[1532,9],axis=0)
x.shape

(1536, 54)

In [28]:
for i in range(n):    
    n_unique,n_count = np.unique(x[:,i],return_counts=True)
    if len(n_unique) < 5:
        print(i,n_unique,n_count)

1 [1. 2.] [891 645]
3 [1. 2. 3.] [479 553 504]
5 [1. 2. 3. 4.] [434 203  90 809]
6 [0. 1.] [ 462 1074]
7 [0. 1.] [ 210 1326]
8 [0. 1.] [ 206 1330]
9 [0. 1.] [ 211 1325]
10 [0. 1.] [ 206 1330]
11 [1. 2. 3.] [563 834 139]
15 [0. 1.] [815 721]
16 [0. 1. 2.] [396 583 557]
18 [0. 1. 2.] [ 193  133 1210]
19 [0. 1.] [1344  192]
20 [0. 1.] [1403  133]
21 [0. 1.] [ 326 1210]
22 [0. 1. 2.] [1340  172   24]
23 [0. 1.] [ 265 1271]
24 [0. 1.] [ 258 1278]
25 [0. 1.] [ 256 1280]
26 [0. 1.] [ 239 1297]
27 [0. 1.] [ 220 1316]
28 [0. 1.] [ 237 1299]
29 [0. 1.] [ 306 1230]
30 [0. 1.] [ 235 1301]
32 [0. 1.] [  18 1518]
34 [0. 1.] [ 230 1306]
35 [0. 1.] [1281  255]
36 [0. 1.] [1241  295]
37 [0. 1.] [1210  326]
38 [0. 1.] [1248  288]
39 [0. 1.] [1164  372]
40 [0. 1.] [645 891]
41 [0. 1.] [891 645]
42 [0. 1.] [1057  479]
43 [0. 1.] [983 553]
44 [0. 1.] [1032  504]
45 [0. 1.] [1097  439]
46 [0. 1.] [980 556]
47 [0. 1.] [1013  523]
48 [0. 1.] [1518   18]
49 [0. 1.] [1102  434]
50 [0. 1.] [1333  203]
51 [0. 1.]

In [29]:
# find binary
i_binary = []
for i in range(n):    
    n_unique,n_count = np.unique(x[:,i],return_counts=True)
    if len(n_unique) == 2:
        i_binary.append(i)
        
print(len(i_binary))

38


In [31]:
x_binary = x[:,i_binary]
x_binary.shape

(1536, 38)

In [33]:
i_all = np.arange(n)
i_all

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53])

In [35]:
i_continuous = np.setdiff1d(i_all,i_binary)
i_continuous

array([ 0,  2,  3,  4,  5, 11, 12, 13, 14, 16, 17, 18, 22, 31, 33, 53])

In [36]:
x_continuous = x[:,i_continuous]
x_continuous.shape

(1536, 16)

In [38]:
# convert {1,2} to {0,1}:
x_binary[:,0] -= 1

np.savetxt('smoking_binary.dat',x_binary,fmt='%i')
np.savetxt('smoking_continuous.dat',x_continuous,fmt='%f')