In [1]:
import numpy as np

In [2]:
#a = np.array([])
#a = []
a = np.empty((1,5))
print(a)

b = np.array([1,-1,1,1,-1])
c = np.array([-1,-1,-1,-1,-1])

[[2.48273508e-312 2.05833592e-312 2.05833592e-312 2.29175545e-312
  2.07955588e-312]]


In [3]:
a = np.append(a, b[np.newaxis,:])
print(a)

[ 2.48273508e-312  2.05833592e-312  2.05833592e-312  2.29175545e-312
  2.07955588e-312  1.00000000e+000 -1.00000000e+000  1.00000000e+000
  1.00000000e+000 -1.00000000e+000]


In [10]:
a = np.empty((1,5))
#print(a)
b = np.array([1,-1,1,1,-1])
a = np.vstack((a, b[np.newaxis,:]))
print(a)

[[ 5.e-324      nan  5.e-324  5.e-324      nan]
 [ 1.e+000 -1.e+000  1.e+000  1.e+000 -1.e+000]]


In [21]:
a = np.array([])
#print(a)
b = np.array([1,-1,1,1,-1])
c = np.array([-1,-1,-1,-1,-1])

a = np.vstack([a, b[np.newaxis,:]]) if a.size else b

a = np.vstack([a, c[np.newaxis,:]]) if a.size else c

print(a)

[[ 1 -1  1  1 -1]
 [-1 -1 -1 -1 -1]]


In [16]:
a = np.empty([])

In [17]:
a.size

1

In [19]:
a = np.array([])
#print(a)
b = np.array([[1,2,3,4,5],[10,20,30,40,50]])
a = np.vstack([a, b]) if a.size else b
print(a)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
